### ISSUE TITLE
Hi Alexander is plex ready for pyside 2 and qt5 for maya 2017?

### ISSUE THREAD

**Issue by tws0002** [richteralexander/plex#10]
Hi Alexander, 

Thanks for this open source pipeline. I was waiting for so long!! finally u release it. 

Question 
- is plex ready for PySide 2 and qt5 for Maya 2017?
- Can we have a more detail installation instruction for plex?
- where can we see your presentation on FMX?

Thanks 
Desmond

**Comment by richteralexander** [comment]
Thanks for the wait!

At the moment Maya is not really running since I focused on some core parts but it will in the next days and also with 2017. I didn't try PySide2 so I couldn't say.

The presentation is currently online:
https://livestream.com/accounts/10071884/events/7339552/videos/155507577

I appreciate feedback if things are working on specific platforms since I can't test for everything.
There will be a patch day (probably every Sunday) where I try to hit milestones.

What do you miss in setting it up?
(I will provide a video the moment it arrives at a specific state)

Best, Alex

**Comment by tws0002** [comment]
Thanks for the quick reply. 

I just start to work on studio pipeline. I don't have any coding background!! but I keep learning hard on this part. Hope I can learn something from you. hope u don't mind if I asking for some stupid question. 

I having some issues when editing on project.yml and software.yml. 

3. master pipeline
set pipeline PATHs: $pipeline/data/pipeline.yml
set project data: $pipeline/data/project/default/...
project.yml
software.yml

4. project pipeline
copy $pipeline/data to $project/pipeline/data path
set $project/pipeline PATHs: $pipeline/data/pipeline.yml
set $project path: $pipeline/data/project/default/project.yml
To overwrite scripts in the project: create the folder and file at the same path location

it doesn't work on me after I do the edit!! 

Thanks 
Desmond

**Comment by richteralexander** [comment]
Does it work BEFORE you edit it?
Ignore 4. project pipeline at the moment since it is just vital when you have more than one layer of pipeline.

1. you need to have your pipeline-path set in $pipeline/data/pipeline.yml PATHS.
2. try data/exe/arDesktop.exe (on Windows)

This should work if you have Python2.7, Yaml and PySide installed properly.

I probably need some weeks to develop a stable version but good feedback it vital since I can't test for every situation. So please always add your error message:
https://github.com/richteralexander/plex/wiki/How-to-Contribute

Best, Alex
