### ISSUE TITLE
Maya Shelf icon missing 

### ISSUE THREAD

**Issue by tws0002** [richteralexander/plex#15]
Hey Alex 

here is the error in Maya 

`// Warning: file: K:/SES/Library/plex/software/maya/shelf/shelf_plex.mel line 316: Pixmap file //sasquatch/studentsmaterials/Programme/plex/img/software/maya/shelf/shelf_help35.png not found, using default.`

seems like the shelf_plex.mel all the icon path is not linked to the correct path!!

for now, we still cannot test save/load function in Plex arPipeline for Maya, Nuke and Houdini right?

Thanks
Desmond

**Comment by richteralexander** [comment]
yeah. normally the shelf has absolute paths ... it is a mess. 
I think there are some hacks but I need to explore them first.
A current solution would be: "find&replace" to your path current in the shelf. not pretty but it works.

Yeah, save and load are not ported for the moment.

**Comment by tws0002** [comment]
yes, "find&replace" is the good way to fix it for now!! 
when will u plan to release the full function version of plex?

**Comment by richteralexander** [comment]
fix the shelf icon bug: 
added to maya img path the shelf path and deleted the path in the shelfs

XBMLANGPATH:
      - !env [IMG_PATH, /software/maya/shelf]

**Comment by richteralexander** [comment]
**plex** was always meant as a framework to add plugins and your own scripts to grow.
It is less a toolset and more an environment to share work. 
For example: you create your own shelf, throw it in _maya/shelf_ and everyone using the pipeline will have the same shelf, same with plugins, scripts etc.

I have an old version of the Breaking Point pipeline (with save, load and others) but there is a big difference between a script working for a project or company and sharing it publicly. It takes a lot of time to port this scripts since they should be much more flexible etc.
Not sure. Maybe in the next weeks. My schedule it quite packed at the moment.
Working on a plugin to create precise Tension Maps and dynamic Microstructure for more realistic skin.

Thank you for your feedback!

**Comment by tws0002** [comment]
I see. Thanks for the advice. 
I will keep doing the test on plex when u have a new update. 
the plugin u working on is plan to release for public or create for in-house tools?

Thanks for the fix.

**Comment by richteralexander** [comment]
Thanks for that!
Yeah, the Tension Map and Dynamic Microstructure nodes are planned to be free for everyone. 
(open source is still in question)
